Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.6.8"
    config.vm.hostname = "virtualbox-vm"
    config.vm.network "private_network", ip: "172.16.16.16"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "virtualbox-vm"
        vb.memory = 1024
        vb.cpus = 1
    end
  
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            # Create khanhnguyen user
            useradd -s /bin/bash -d /home/khanhnguyen/ -m -G sudo khanhnguyen
            echo 'khanhnguyen ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            mkdir -p /home/khanhnguyen/.ssh && chown -R khanhnguyen /home/khanhnguyen/.ssh
            echo #{ssh_pub_key} >> /home/khanhnguyen/.ssh/authorized_keys
        SHELL
    end
  end